source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'EndingViolence' do
	pod 'RealmSwift'
	pod 'Alamofire', '~> 3.0'
	pod 'ReachabilitySwift'
end